# Canlı (Production) sunucu ortamı veritabanı ayarları
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Canlı ortamda tabloların kaza ile bozulmaması ve performans ayarları
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
