# Geliştirme (Local Docker) ortamı veritabanı ayarları
spring.datasource.url=jdbc:postgresql://localhost:5436/todo
spring.datasource.username=postgres
spring.datasource.password=8552

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
